## YAML Template.
---
server:
    port: 9900

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
spring:
    cloud:
        gateway:
            routes:
                - id: path_route
                  uri: http://localhost:8123/
                  predicates:
                  - Path=/getEndpoint
